name: Build Faiss

on:
  ### Just stop running actions by push
  #push:

  ### Manual trigger
  workflow_dispatch:

  ### Trigger every week
  # schedule:
  #   # Every Monday, UTC 0:00 (JST 9:00)
  #   - cron: 0 0 * * 1

jobs:
  build-faiss:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false   # Keep running even if some runs fail
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"] 
        faiss-label: ["main", "nightly"]
        faiss-version: ["1.7.4", "1.7.3"]
        exclude: 
        - python-version: "3.10"   # Faiss 1.7.3 main on {ubuntu, mac, win} doesn't support py3.10
          faiss-label: "main"
          faiss-version: "1.7.3"
        - os: "windows-latest"    # Faiss 1.7.3 main on win doesn't support py3.9
          python-version: "3.9"   
          faiss-label: "main"
          faiss-version: "1.7.3"
          
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Install the latest miniconda. The "test" environment is activated. This works for windows as well.
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Install faiss ${{ matrix.faiss-version }} for main channel
      shell: bash -l {0}    # to activate conda
      if: matrix.faiss-label == 'main'
      run: |
        conda install -c pytorch faiss-cpu==${{ matrix.faiss-version }}
        
    - name: Install faiss ${{ matrix.faiss-version }} for nightly channel
      shell: bash -l {0}    # to activate conda
      if: matrix.faiss-label == 'nightly'
      run: |
        conda install -c "pytorch/label/nightly" faiss-cpu==${{ matrix.faiss-version }} 
       
    - name: Run
      shell: bash -l {0}    # to activate conda
      run: |
        python --version               
        python run.py

