name: Build Faiss

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false   # Keep running even if some runs fail
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"] 
        faiss_label: ["main", "nightly"]
          
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        if [ "${{ matrix.faiss_label }}" = "main" ]; then
          conda install -c pytorch faiss-cpu
        fi
          conda install -c "pytorch/label/nightly" faiss-cpu 

        
    - name: Run
      run: |
        which conda        
        which python
        python --version
               
        python run.py

